### ISSUE TITLE
read: message too long

### ISSUE THREAD

**Issue by HashimTheArab** [Sandertv/go-raknet#26] opened 2023-11-16 03:15 UTC
This happens on some servers, mostly nethergames, but not all of the time

It happens with raknet.Dial but not with net.Dial("udp", addr)
It will happen the first time dialing, and then not happen for a while, unless I turn off my wifi and turn it back on on my PC

It occurs at: https://github.com/Sandertv/go-raknet/blob/c8d5d29170d34294d2420cf07daa4f53097b9c65/dial.go#L438

Using the terminal ping command and disabling fragmentation 
![image](https://github.com/Sandertv/go-raknet/assets/13991048/9af8a468-de3b-4fed-8cfd-c6436fa5e632)

**Comment by Adrian8115** [comment] 2023-12-23 21:14
your mtu is too lowm youneed to set it higher!

**Comment by Sandertv** [comment] 2024-05-04 09:53
Is this still an issue these days?

**Comment by Sandertv** [comment] 2024-05-10 09:44
Closing this due to a lack of reproducibility. Please feel free to update if this is still an issue and I will re-open the issue.

**Closed by Sandertv** 2024-05-10 09:44 UTC
Labels: bug
